@startuml SQ
autonumber
title SD29.4. Hoàn thành công việc
actor "Actor" as actor
boundary "TaskView" as view
control "TaskController" as controller
entity "TaskRepository" as model
database "Database" as database
activate actor
actor -> view : check done task
deactivate actor
activate view
view -> view: display confirmation dialog
alt click confirm
view -> controller : call api PUT /change-state
activate controller
controller -> model : inject repository
activate model
model -> database : update task to done state
activate database
database --> model : callback
deactivate database
model --> controller : callback
deactivate model
controller --> view : return mesage
deactivate controller
view -> view: display mesage
view -> controller: call api GET /list
activate controller
controller -> model: inject repository
activate model
model -> database: find data
activate database
database --> model: return data
deactivate database
model --> controller: return list objects
deactivate model
controller --> view: return list
deactivate controller
view -> view: display data
else click cancel
view -> view: close dialog
activate view
deactivate view
deactivate view
end
@enduml