//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_W6
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        public string MaHS { get; set; }
        public string Ten { get; set; }
        public string QueQuan { get; set; }
        public System.DateTime NgayThangNamSinh { get; set; }
        public string CMND { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
        public Nullable<double> Diem { get; set; }
    }
}
