//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_W6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int rno { get; set; }
        public string address { get; set; }
        public Nullable<int> capacity { get; set; }
    }
}
