const fs = require("fs");

const tags = [
  "automation",
  "CRM",
  "technology",
  "data visualization",
  "IT consulting",
  "fintech solutions",
  "AR",
  "team collaboration",
  "app deployment",
  "API management",
  "wearables",
  "entrepreneurship",
  "e-commerce platform",
  "digital security",
  "IoT networks",
  "IT security",
  "GDPR",
  "system architecture",
  "GDPR",
  "edge computing",
  "data analytics",
  "VR",
  "web development",
  "automation",
  "IT security",
  "marketing",
  "green technology",
  "infrastructure as code",
  "social media",
  "B2B marketing",
  "IT consulting",
  "brand",
  "technology",
  "cloud infrastructure",
  "digital innovation",
  "customer acquisition",
  "5G technology",
  "data pipeline",
  "data-driven",
  "app development",
  "application security",
  "responsive design",
  "5G technology",
  "engineering",
  "marketing tech",
  "website optimization",
  "brand",
  "cross-border payments",
  "information systems",
  "streaming data",
  "data-driven decision making",
  "business growth",
  "streaming data",
  "network security",
  "predictive analytics",
  "cloud architecture",
  "enterprise cloud",
  "cloud",
  "cloud security",
  "data science",
  "cyber defense",
  "growth hacking",
  "cybersecurity",
  "network architecture",
  "AR",
  "IoT devices",
  "machine learning",
  "UX/UI design",
  "digital innovation",
  "data protection",
  "edge computing",
  "AI models",
  "responsive design",
  "financial services",
  "cloud consulting",
  "machine learning",
  "cloud backup",
  "cyber defense strategies",
  "digital security",
  "IT management",
  "green technology",
  "data privacy",
  "digital assets",
  "fintech startups",
  "product management",
  "design",
  "online marketing",
  "performance tuning",
  "data-driven",
  "web development",
  "cloud",
  "internet",
  "IoT networks",
  "data pipeline",
  "global market",
  "cybersecurity",
  "big data",
  "design",
  "engineering",
  "B2B",
  "mobile",
  "digital marketing strategy",
  "business intelligence",
  "advertising",
  "business intelligence",
  "future tech",
  "cloud apps",
  "growth strategy",
  "enterprise solutions",
  "cloud storage",
  "cloud infrastructure",
  "technology stack",
  "IoT",
  "digital marketing strategy",
  "sales",
  "SaaS",
  "security",
  "e-commerce solutions",
  "innovation",
  "enterprise",
  "growth",
  "performance tuning",
  "future trends",
  "web development",
  "business continuity",
  "cloud automation",
  "brand",
  "machine learning",
  "smart cities",
  "smart cities",
  "e-commerce",
  "enterprise solutions",
  "cloud apps",
  "productivity",
  "cyber defense strategies",
  "data management",
  "cloud",
  "microservices",
  "AI models",
  "marketing tech",
  "remote work",
  "agile",
  "security",
  "digital assets",
  "AR",
  "tech trends",
  "network architecture",
  "user experience",
  "digital assets",
  "predictive modeling",
  "mobile",
  "remote work",
  "predictive modeling",
  "disruptive technology",
  "salesforce",
  "disruptive technology",
  "IoT solutions",
  "mobile",
  "cross-platform",
  "quantum computing",
  "SaaS model",
  "growth",
  "cloud hosting",
  "e-commerce platform",
  "sustainability",
  "blockchain",
  "data science",
  "cloud security",
  "data pipeline",
  "cyber defense",
  "UI/UX",
  "blockchain technology",
  "data analytics",
  "AI ethics",
  "digital security",
  "cloud storage",
  "cloud architecture",
  "growth hacking",
  "business intelligence",
  "project management",
  "business intelligence tools",
  "VR",
  "user experience",
  "frontend development",
  "leadership",
  "disruptive technology",
  "technology ecosystem",
  "team collaboration",
  "technology solutions",
  "data protection laws",
  "robotics",
  "fintech startups",
  "digital marketing strategy",
  "B2B",
  "performance tuning",
  "online marketing",
  "future tech",
  "network security",
  "tech investment",
  "remote work",
];

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRandomHexColor() {
  const hexCharacters = "0123456789ABCDEF";
  let color = "#";
  for (let i = 0; i < 6; i++) {
    color += hexCharacters[getRandomInt(0, hexCharacters.length - 1)];
  }
  return color;
}

function generateEmployeeData() {
  return tags.map((tagName) => ({
    name: tagName,
    colorCode: getRandomHexColor(),
    kind: getRandomInt(1, 4),
  }));
}

function jsonToCsv(data) {
  const headers = Object.keys(data[0]);
  const rows = data.map((row) =>
    headers.map((header) => `"${row[header]}"`).join(",")
  );
  return [headers.join(","), ...rows].join("\n");
}

function saveToCsv(fileName) {
  const employeeData = generateEmployeeData();
  const csvContent = jsonToCsv(employeeData);
  fs.writeFileSync(fileName, csvContent, "utf8");
  console.log(`File CSV đã được tạo: ${fileName}`);
}

const timestamp = new Date().toISOString().replace(/[-T:.Z]/g, "");
const fileName = `tags_${timestamp}.csv`;
saveToCsv(fileName);
