services:
  mongo:
    image: mongo:8.0.4
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123654
    volumes:
      - data:/data/db
      - config:/data/configdb

volumes:
  data:
  config:
# URI Connect to Compass: mongodb://admin:admin123654@localhost:27018
