//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangTienLoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgayLe
    {
        public int MaNL { get; set; }
        public System.DateTime Ngay { get; set; }
        public string SuKien { get; set; }
    }
}
