//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangTienLoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamConBan
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public double GiaBan { get; set; }
        public double GiaGoc { get; set; }
        public bool TrangThai { get; set; }
        public byte[] Hinh { get; set; }
    }
}
