//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangTienLoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPConHan
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public System.DateTime NgayNhapKho { get; set; }
        public System.DateTime HSD { get; set; }
        public int SLTonKho { get; set; }
        public bool TrangThai { get; set; }
    }
}
