@startuml SQ

autonumber

title SD17. Cập nhật chi tiết bài học

actor "Instructor"
boundary "UpdateLessonDetails"
boundary "CreateDocument"
boundary "CreateComment"
control "DocumentService"
control "DocumentController"
entity "DocumentModel"
database "Database" as Database
activate Instructor
Instructor -> UpdateLessonDetails: click "Create Document"
activate UpdateLessonDetails
UpdateLessonDetails -> CreateDocument: navigate(\n"/create-document")
deactivate UpdateLessonDetails
activate CreateDocument
Instructor -> CreateDocument: input {title, description, content}
CreateDocument -> DocumentService: handleCreate()
activate DocumentService
DocumentService -> DocumentController: createDocument(formData)
activate DocumentController
DocumentController -> DocumentModel: call model
activate DocumentModel
DocumentModel -> Database: Document.create()
deactivate DocumentModel
activate Database
Database --> DocumentController: callback
deactivate Database
DocumentController --> DocumentService: send res.json
deactivate DocumentController
DocumentService --> CreateDocument: callback
deactivate DocumentService

alt input is empty
CreateDocument -> CreateDocument: display alert
else input is not empty
CreateDocument -> UpdateLessonDetails: navigate(\n"/update-lesson-details")
deactivate CreateDocument
end

opt delete document
Instructor -> UpdateLessonDetails: click "Delete" button on a document
ref over UpdateLessonDetails
**SD17a. Delete document**
end ref
end

opt create comment
Instructor -> UpdateLessonDetails: click "Leave Comment"
deactivate Instructor
activate UpdateLessonDetails
UpdateLessonDetails -> CreateComment: navigate(\n"/create-comment")
deactivate UpdateLessonDetails
ref over CreateComment
**SD17b. Create comment**
end ref
end
@enduml