services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbit-mq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin@2o23.hcm
    volumes:
      - data:/var/lib/rabbitmq
volumes:
  data:
