@startuml SQ
autonumber
title SD12. Quản lý kỳ thanh toán
actor "Actor" as actor
boundary "PaymentPeriod\nView" as view
control "PaymentPeriod\nController" as controller
entity "PaymentPeriod\nRepository" as model
database "Database" as database
activate actor
actor -> view : access to
deactivate actor
activate view
view -> controller : call api GET /list
activate controller
controller -> model : inject repository
activate model
model -> database : find data
activate database
database --> model : return data
deactivate database
model --> controller: return list objects
deactivate model
controller --> view : return list object
deactivate controller
view -> view: display data
activate view
deactivate view
deactivate view
group frg [//TH2. Người dùng duyệt kỳ thanh toán//]
ref over actor
SD12.1. Duyệt kỳ thanh toán
end ref
end
group frg [//TH3. Người dùng tính lại kỳ thanh toán//]
ref over actor
SD12.2. Tính lại kỳ thanh toán
end ref
end
group frg [//TH4. Người dùng bỏ giao dịch ra khỏi kỳ thanh toán//]
ref over actor
SD12.3. Bỏ giao dịch ra khỏi kỳ thanh toán
end ref
end
@enduml