@startuml SQ
autonumber
title SD22. Quản lý key
actor "Actor" as actor
boundary "KeyInformationView" as view
control "KeyInformationController" as controller
entity "KeyInformationRepository" as model
database "Database" as database
activate actor
actor -> view : access to
activate view
view -> controller : call api GET /list
activate controller
controller -> model : inject repository
activate model
model -> database : find data
activate database
database --> model : return data
deactivate database
model --> controller: return list objects
deactivate model
controller --> view : return list object
deactivate controller
view -> view: display data
group frg [//TH1. Người dùng tìm kiếm key//]
actor -> view : enter search criterias
deactivate actor
view -> view: update data display
activate view
deactivate view
deactivate view
end
group frg [//TH2. Người dùng tạo key//]
ref over actor
SD22.1. Tạo key
end ref
end
group frg [//TH3. Người dùng sửa key//]
ref over actor
SD22.2. Sửa key
end ref
end
group frg [//TH4. Người dùng xóa key//]
ref over actor
SD22.3. Xóa key
end ref
end
group frg [//TH5. Người dùng xuất tệp Excel//]
ref over actor
SD22.4. Xuất tệp Excel
end ref
end
group frg [//TH6. Người dùng giải mã mật khẩu//]
ref over actor
SD22.5. Giải mã mật khẩu key
end ref
end
@enduml