@startuml SQ
autonumber
title SD22.4. Xuất tệp Excel
actor "Actor" as actor
boundary "KeyInformationView" as view
control "KeyInformationController" as controller
control "ExcelService" as service
entity "KeyInformationRepository" as model
database "Database" as database
activate actor
actor -> view : click export button
activate view
view -> view: open confirmation dialog
alt click confirm
view -> controller : call api POST /export-excel
activate controller
controller -> model : inject repository
activate model
model -> database : find data
activate database
database --> model : return data
deactivate database
model --> controller : return list objects
deactivate model
controller -> service: process data
activate service
service --> controller : callback
deactivate service
controller --> view : return file Excel
deactivate controller
view -> actor: download file Excel
deactivate actor
else click cancel
view -> view: close dialog
activate view
deactivate view
deactivate view
end
@enduml