import {
  ArrowLeftRightIcon,
  FrownIcon,
  HeadsetIcon,
  HeartIcon,
  KeyIcon,
  LaughIcon,
  SmileIcon,
  SparklesIcon,
  SquareCheckBigIcon,
  ThumbsUpIcon,
  UserIcon,
} from "lucide-react";
import {
  CATEGORY_CONFIG,
  DEBIT_CONFIG,
  DEPARTMENT_CONFIG,
  EMPLOYEE_CONFIG,
  KEY_INFORMATION_CONFIG,
  KEY_INFORMATION_GROUP_CONFIG,
  KEY_INFORMATION_GROUP_PERMISSION_CONFIG,
  KEY_INFORMATION_TAG_CONFIG,
  NOTIFICATION_GROUP_CONFIG,
  ORGANIZATION_CONFIG,
  ORGANIZATION_PERMISSION_CONFIG,
  PAYMENT_PERIOD_CONFIG,
  PROFILE_CONFIG,
  PROJECT_CONFIG,
  PROJECT_PERMISSION_CONFIG,
  PROJECT_TAG_CONFIG,
  ROLE_CONFIG,
  SERVICE_CONFIG,
  SERVICE_GROUP_CONFIG,
  SERVICE_GROUP_PERMISSION_CONFIG,
  SERVICE_NOTIFICATION_GROUP_CONFIG,
  SERVICE_SCHEDULE_CONFIG,
  SERVICE_TAG_CONFIG,
  TASK_CONFIG,
  TRANSACTION_CONFIG,
  TRANSACTION_GROUP_CONFIG,
  TRANSACTION_GROUP_PERMISSION_CONFIG,
  TRANSACTION_TAG_CONFIG,
  USER_NOTIFICATION_GROUP_CONFIG,
} from "./PageConfigDetails";

const PAGE_CONFIG = {
  ...TRANSACTION_CONFIG,
  ...ROLE_CONFIG,
  ...EMPLOYEE_CONFIG,
  ...PROFILE_CONFIG,
  ...DEPARTMENT_CONFIG,
  ...TRANSACTION_GROUP_CONFIG,
  ...TRANSACTION_GROUP_PERMISSION_CONFIG,
  ...SERVICE_GROUP_CONFIG,
  ...SERVICE_GROUP_PERMISSION_CONFIG,
  ...KEY_INFORMATION_GROUP_CONFIG,
  ...KEY_INFORMATION_GROUP_PERMISSION_CONFIG,
  ...ORGANIZATION_CONFIG,
  ...ORGANIZATION_PERMISSION_CONFIG,
  ...CATEGORY_CONFIG,
  ...TRANSACTION_TAG_CONFIG,
  ...SERVICE_TAG_CONFIG,
  ...KEY_INFORMATION_TAG_CONFIG,
  ...PROJECT_TAG_CONFIG,
  ...NOTIFICATION_GROUP_CONFIG,
  ...USER_NOTIFICATION_GROUP_CONFIG,
  ...PROJECT_CONFIG,
  ...TASK_CONFIG,
  ...PROJECT_PERMISSION_CONFIG,
  ...KEY_INFORMATION_CONFIG,
  ...SERVICE_CONFIG,
  ...SERVICE_NOTIFICATION_GROUP_CONFIG,
  ...SERVICE_SCHEDULE_CONFIG,
  ...DEBIT_CONFIG,
  ...PAYMENT_PERIOD_CONFIG,
};

const SESSION_KEY_PAGES: Set<string> = new Set([
  PAGE_CONFIG.TRANSACTION.name,
  PAGE_CONFIG.TRANSACTION_GROUP.name,
  PAGE_CONFIG.SERVICE_GROUP.name,
  PAGE_CONFIG.KEY_INFORMATION_GROUP.name,
  PAGE_CONFIG.ORGANIZATION.name,
  PAGE_CONFIG.CATEGORY.name,
  PAGE_CONFIG.TRANSACTION_TAG.name,
  PAGE_CONFIG.SERVICE_TAG.name,
  PAGE_CONFIG.KEY_INFORMATION_TAG.name,
  PAGE_CONFIG.PROJECT_TAG.name,
  PAGE_CONFIG.NOTIFICATION_GROUP.name,
  PAGE_CONFIG.PROJECT.name,
  PAGE_CONFIG.KEY_INFORMATION.name,
  PAGE_CONFIG.SERVICE.name,
  PAGE_CONFIG.DEBIT.name,
  PAGE_CONFIG.PAYMENT_PERIOD.name,
]);

const DECRYPT_FIELDS = {
  TRANSACTION_GROUP: ["name", "description"],
  SERVICE_GROUP: ["name", "description"],
  KEY_INFORMATION_GROUP: ["name", "description"],
  ORGANIZATION: ["logo", "name"],
  CATEGORY: ["description", "name"],
  TAG: ["colorCode", "name"],
  NOTIFICATION_GROUP: ["name", "description"],
  PROJECT: ["logo", "name", "note", "organization.name", "tag.colorCode"],
  TASK: ["name", "note", "document"],
  KEY_INFORMATION: [
    "name",
    "additionalInformation",
    "document",
    "keyInformationGroup.name",
    "organization.name",
    "tag.name",
    "tag.colorCode",
    "description",
  ],
  SERVICE: [
    "description",
    "money",
    "name",
    "serviceGroup.name",
    "tag.name",
    "tag.colorCode",
  ],
  SERVICE_NOTIFICATION_GROUP: ["notificationGroup.name"],
  TRANSACTION: [
    "money",
    "name",
    "document",
    "note",
    "transactionGroup.name",
    "category.name",
    "tag.name",
    "tag.colorCode",
  ],
  DEBIT: [
    "money",
    "name",
    "document",
    "note",
    "transactionGroup.name",
    "category.name",
    "tag.name",
    "tag.colorCode",
  ],
  PAYMENT_PERIOD: ["name", "totalIncome", "totalExpenditure"],
  CHAT_ROOM: ["lastMessage.content", "lastMessage.document"],
  CHAT_HISTORY: ["message"],
  MESSAGE: ["content", "document", "parent.content", "parent.document"],
};

const CONVER_DATE_FIELDS = {
  CHAT_ROOM: ["lastLogin", "lastMessage.createdDate"],
  MESSAGE: ["createdDate", "parent.createdDate"],
  CHAT_HISTORY: ["createdDate"],
};

const GEMINI_BOT_CONFIG = {
  id: -99999999,
  name: "Gemini AI",
  description: "Gemini 2.0 Flash",
  icon: SparklesIcon,
  kind: 3,
};

const MESSAGE_REACTION_KIND_MAP = {
  LIKE: {
    value: 1,
    label: "Thích",
    icon: ThumbsUpIcon,
    emoji: "👍",
    className: "text-blue-600 dark:bg-blue-900 dark:text-blue-300",
  },
  HEART: {
    value: 2,
    label: "Yêu thích",
    icon: HeartIcon,
    emoji: "❤️",
    className: "text-rose-600 dark:bg-rose-900 dark:text-rose-300",
  },
  CRY: {
    value: 3,
    label: "Buồn",
    icon: FrownIcon,
    emoji: "😭​",
    className: "text-sky-600 dark:bg-sky-900 dark:text-sky-300",
  },
  JOY: {
    value: 4,
    label: "Hạnh phúc",
    icon: SmileIcon,
    emoji: "☺️",
    className: "text-yellow-600 dark:bg-yellow-900 dark:text-yellow-300",
  },
  LAUGH: {
    value: 5,
    label: "Haha",
    icon: LaughIcon,
    emoji: "😂​",
    className: "text-amber-600 dark:bg-amber-900 dark:text-amber-300",
  },
};

const SIDEBAR_MENUS = [
  {
    name: "Quản lý giao dịch",
    icon: <ArrowLeftRightIcon size={20} />,
    items: [
      PAGE_CONFIG.TRANSACTION,
      PAGE_CONFIG.TRANSACTION_GROUP,
      PAGE_CONFIG.CATEGORY,
      PAGE_CONFIG.PAYMENT_PERIOD,
      PAGE_CONFIG.DEBIT,
      PAGE_CONFIG.TRANSACTION_TAG,
    ],
  },
  {
    name: "Quản lý dịch vụ",
    icon: <HeadsetIcon size={20} />,
    items: [
      PAGE_CONFIG.SERVICE,
      PAGE_CONFIG.SERVICE_GROUP,
      PAGE_CONFIG.NOTIFICATION_GROUP,
      PAGE_CONFIG.SERVICE_TAG,
    ],
  },
  {
    name: "Quản lý key",
    icon: <KeyIcon size={20} />,
    items: [
      PAGE_CONFIG.KEY_INFORMATION,
      PAGE_CONFIG.KEY_INFORMATION_GROUP,
      PAGE_CONFIG.KEY_INFORMATION_TAG,
    ],
  },
  {
    name: "Quản lý ghi chú",
    icon: <SquareCheckBigIcon size={20} />,
    items: [
      PAGE_CONFIG.ORGANIZATION,
      PAGE_CONFIG.PROJECT,
      PAGE_CONFIG.PROJECT_TAG,
    ],
  },
  {
    name: "Quản lý người dùng",
    icon: <UserIcon size={20} />,
    items: [PAGE_CONFIG.EMPLOYEE, PAGE_CONFIG.ROLE, PAGE_CONFIG.DEPARTMENT],
  },
];

export {
  PAGE_CONFIG,
  SIDEBAR_MENUS,
  SESSION_KEY_PAGES,
  DECRYPT_FIELDS,
  CONVER_DATE_FIELDS,
  GEMINI_BOT_CONFIG,
  MESSAGE_REACTION_KIND_MAP,
};
