@startuml SQ
autonumber
title SD19a. Change course visibility
boundary "views/\nUpdateCourseDetailPage" as UpdateCourseDetailPage
control "CourseService"
control "CourseController"
entity "CourseModel"
database "Database" as Database
activate UpdateCourseDetailPage
UpdateCourseDetailPage -> CourseService: changeCourseVisibility(courseId, visibility)
activate CourseService
CourseService -> CourseController: router.put(\n"/changeCourseVisibility:id",\nchangeCourseVisibility)
activate CourseController
CourseController -> CourseModel: call model
activate CourseModel
CourseModel -> Database: Course.findById(courseId)
deactivate CourseModel
activate Database
Database --> CourseController: return course
deactivate Database
CourseController -> CourseModel: call model
activate CourseModel
CourseModel -> Database: course.updateOne({visibility})
deactivate CourseModel
activate Database
Database --> CourseController: callback
deactivate Database
CourseController --> CourseService: send res.json
deactivate CourseController
CourseService --> UpdateCourseDetailPage: display message
deactivate UpdateCourseDetailPage
deactivate CourseService

@enduml