//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDanThanhPho
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongDan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongDan()
        {
            this.CanCuocCongDans = new HashSet<CanCuocCongDan>();
            this.TamTruTamVangs = new HashSet<TamTruTamVang>();
        }
    
        public int MaCD { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public int GioiTinh { get; set; }
        public string NgheNghiep { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public int TinhTrang { get; set; }
        public int HonNhan { get; set; }
        public string TenTK { get; set; }
        public string MatKhau { get; set; }
        public int LoaiTK { get; set; }
        public double SoDu { get; set; }
        public byte[] Hinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanCuocCongDan> CanCuocCongDans { get; set; }
        public virtual KhaiSinh KhaiSinh { get; set; }
        public virtual KhaiTu KhaiTu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TamTruTamVang> TamTruTamVangs { get; set; }
        public virtual ThuongTru ThuongTru { get; set; }
    }
}
