//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDanThanhPho
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhaiTu
    {
        public int MaCD { get; set; }
        public string NguyenNhan { get; set; }
        public System.DateTime NgayTu { get; set; }
        public System.DateTime NgayKhai { get; set; }
        public string NguoiKhai { get; set; }
        public string QuanHeVoiNguoiDuocKhai { get; set; }
    
        public virtual CanCuocCongDan CanCuocCongDan { get; set; }
        public virtual CongDan CongDan { get; set; }
    }
}
