//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongDanThanhPho
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CanCuocCongDan> CanCuocCongDans { get; set; }
        public virtual DbSet<CongDan> CongDans { get; set; }
        public virtual DbSet<HoKhau> HoKhaus { get; set; }
        public virtual DbSet<KetHon> KetHons { get; set; }
        public virtual DbSet<KhaiSinh> KhaiSinhs { get; set; }
        public virtual DbSet<KhaiTu> KhaiTus { get; set; }
        public virtual DbSet<LyHon> LyHons { get; set; }
        public virtual DbSet<TamTruTamVang> TamTruTamVangs { get; set; }
        public virtual DbSet<Thue> Thues { get; set; }
        public virtual DbSet<ThuongTru> ThuongTrus { get; set; }
        public virtual DbSet<vCanCuocCongDan> vCanCuocCongDans { get; set; }
        public virtual DbSet<vHoKhau> vHoKhaus { get; set; }
        public virtual DbSet<vKetHon> vKetHons { get; set; }
        public virtual DbSet<vKhaiSinh> vKhaiSinhs { get; set; }
        public virtual DbSet<vKhaiTu> vKhaiTus { get; set; }
        public virtual DbSet<vLyHon> vLyHons { get; set; }
        public virtual DbSet<vTamTruTamVang> vTamTruTamVangs { get; set; }
        public virtual DbSet<vThue> vThues { get; set; }
        public virtual DbSet<vThuongTru> vThuongTrus { get; set; }
    
        [DbFunction("Entities", "fTimKiemCanCuocCongDan")]
        public virtual IQueryable<fTimKiemCanCuocCongDan_Result> fTimKiemCanCuocCongDan(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTimKiemCanCuocCongDan_Result>("[Entities].[fTimKiemCanCuocCongDan](@tk)", tkParameter);
        }
    
        [DbFunction("Entities", "fTimKiemHoKhau")]
        public virtual IQueryable<fTimKiemHoKhau_Result> fTimKiemHoKhau(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTimKiemHoKhau_Result>("[Entities].[fTimKiemHoKhau](@tk)", tkParameter);
        }
    
        [DbFunction("Entities", "fTimKiemKetHon")]
        public virtual IQueryable<fTimKiemKetHon_Result> fTimKiemKetHon(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTimKiemKetHon_Result>("[Entities].[fTimKiemKetHon](@tk)", tkParameter);
        }
    
        [DbFunction("Entities", "fTimKiemKhaiSinh")]
        public virtual IQueryable<fTimKiemKhaiSinh_Result> fTimKiemKhaiSinh(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTimKiemKhaiSinh_Result>("[Entities].[fTimKiemKhaiSinh](@tk)", tkParameter);
        }
    
        [DbFunction("Entities", "fTimKiemKhaiTu")]
        public virtual IQueryable<fTimKiemKhaiTu_Result> fTimKiemKhaiTu(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTimKiemKhaiTu_Result>("[Entities].[fTimKiemKhaiTu](@tk)", tkParameter);
        }
    
        [DbFunction("Entities", "fTimKiemLyHon")]
        public virtual IQueryable<fTimKiemLyHon_Result> fTimKiemLyHon(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTimKiemLyHon_Result>("[Entities].[fTimKiemLyHon](@tk)", tkParameter);
        }
    
        [DbFunction("Entities", "fTimKiemTamTruTamVang")]
        public virtual IQueryable<fTimKiemTamTruTamVang_Result> fTimKiemTamTruTamVang(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTimKiemTamTruTamVang_Result>("[Entities].[fTimKiemTamTruTamVang](@tk)", tkParameter);
        }
    
        [DbFunction("Entities", "fTimKiemThue")]
        public virtual IQueryable<fTimKiemThue_Result> fTimKiemThue(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTimKiemThue_Result>("[Entities].[fTimKiemThue](@tk)", tkParameter);
        }
    
        [DbFunction("Entities", "fTimKiemThuongTru")]
        public virtual IQueryable<fTimKiemThuongTru_Result> fTimKiemThuongTru(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTimKiemThuongTru_Result>("[Entities].[fTimKiemThuongTru](@tk)", tkParameter);
        }
    }
}
