@startuml SQ
autonumber
title SD21. Cập nhật khu vực
actor "Actor" as actor
boundary "HomeView" as homeView
boundary "LocationView" as view
control "LocationController" as controller
entity "LocationRepository" as model
database "Database" as database
activate actor
actor -> homeView: click location icon
activate homeView
homeView -> view: redirect to
deactivate homeView
activate view
view -> controller: call api GET /my-location
activate controller
controller -> model: inject repository
activate model
model -> database: find data
activate database
database --> model: return data
deactivate database
model --> controller: return object
deactivate model
controller --> view: return object
deactivate controller
view -> view: display data
actor -> view: edit information
deactivate actor
view -> controller: call api PUT /update-by-customer
activate controller
controller -> model: inject repository
activate model
model -> database: update data
activate database
database --> model: callback
deactivate database
model --> controller: callback
deactivate model
controller --> view: callback
deactivate controller
view -> view: display success message
activate view
deactivate view
deactivate view
@enduml