name: cms_chat_app
description: "CMS Zalo UTE"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cookiedu_logo.png
    - assets/user_icon.png
    - assets/empty_box.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/cookiedu_logo.png"
