@startuml CD

title CD13. Tạo khóa học

actor "Instructor"
boundary "CreateCourse"
boundary "MyCreatedCourses"
control "CourseService"
control "CourseController"
entity "CourseModel"

Instructor - CreateCourse: \l1. inputData()<&arrow-right>
CreateCourse - CourseService: \l2. handleCreate()<&arrow-right>
CourseService - CourseController: \l3. createCourse()<&arrow-right>
CourseController -- CourseModel: \l<&arrow-bottom>4. Course.create()
CreateCourse -- MyCreatedCourses: \l<&arrow-bottom>5. navigate("/")
@enduml